---
- name: Install OS package prereqs
  apt:
    name:
      - systemd
      - network-manager
      - apparmor
      - docker
      - jq
      - curl
      - dbus
    state: latest
    update_cache: yes

- name: Disable Modem Manager to prevent issues when using serial devices
  service:
    name: ModemManager
    enabled: no
    state: stopped

- name: Set up docker config file
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: Fix kernel dmesg restriction
  sysctl:
    name: kernel.dmesg_restrict
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes

- name: Create config for NetworkManager
  copy:
    src: "{{ networkmanager_file['source'] }}"
    dest: "{{ networkmanager_file['target'] }}"
  loop:
    - source: NetworkManager.conf
      target: /etc/NetworkManager/NetworkManager.conf
    - source: system-connection-default
      target: /etc/NetworkManager/system-connections/default
  loop_control:
    loop_var: networkmanager_file
    label: "{{ networkmanager_file['source']"
  notify:
    - restart networkmanager

- name: Overwrite network interfaces file
  copy:
    src: interfaces
    dest: /etc/network/interfaces
  notify:
    - restart networkmanager

- name: Init folders
  file:
    path: "{{ data_share }}"
    state: directory

- name: Write config
  template:
    src: hassio.j2
    dest: "{{ config }}"
    mode: '0644'

- name: Ensure all changed service are restarted
  meta: flush_handlers

- name: Write config
  template:
    src: hassio.j2
    dest: "{{ config }}"

- name: Read version infos from web
  uri:
    body_format: json
    url: https://version.home-assistant.io/stable.json
  register: hassio_stable_out

- name: Set hassio_version fact
  set_fact:
    hassio_version: "{{ hassio_stable_out['json']['supervisor'] }}"